(() => {
  'use strict';
  const stages = ['Understanding question','Creating research tasks','Searching sources','Extracting facilities','Verifying evidence','Detecting conflicts','Performing geographic analysis','Identifying potential service gaps','Generating report'];
  const apiBase = location.protocol.startsWith('http') ? location.origin : 'http://127.0.0.1:8000';
  const get = id => document.getElementById(id);
  const safe = value => String(value ?? '').replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
  async function api(path, options) { const response = await fetch(`${apiBase}${path}`, {headers:{Accept:'application/json','Content-Type':'application/json'},...options}); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.detail || data?.error?.message || `Request failed (${response.status})`); return data; }
  async function health() { try { await api('/api/health'); get('connection-status').textContent='API connected'; get('connection-status').className='connection online'; } catch (_) { get('connection-status').textContent='API unavailable'; get('connection-status').className='connection offline'; } }
  function progress(project) { get('progress-section').classList.remove('hidden'); const current=(project.progress?.current_stage || project.status).toLowerCase(); const complete=project.progress?.completed_stages || []; get('progress-title').textContent=project.query; get('research-status').textContent=project.status; get('progress-steps').innerHTML=stages.map(stage => { const key=stage.split(' ')[0].toLowerCase(); return `<div class="progress-step ${complete.some(value=>value.toLowerCase().includes(key))?'done':current.includes(key)?'active':''}">${complete.some(value=>value.toLowerCase().includes(key))?'✓ ':''}${stage}</div>`; }).join(''); const alert=get('research-alert'); if(project.status==='failed'){alert.textContent=project.error || 'Research failed.';alert.classList.remove('hidden');}else alert.classList.add('hidden'); }
  function display(project, report, geography) { progress(project); const facilities=report?.facilities || []; const sources=report?.sources || []; const results=project.intermediate_results || {}; get('metric-grid').innerHTML=[['Research status',project.status],['Sources reviewed',results.source_count ?? sources.length],['Facilities identified',results.facility_count ?? facilities.length],['Service assessments',results.service_gap_assessment_count ?? '—']].map(([name,value])=>`<article><span>${safe(name)}</span><strong>${safe(value)}</strong></article>`).join(''); get('facility-table').innerHTML=facilities.length?facilities.map(f=>`<tr><td><strong>${safe(f.name)}</strong></td><td>${safe([f.city,f.state].filter(Boolean).join(', ')||f.address||'Not documented')}</td><td>${safe((f.facility_type||'Not documented').replaceAll('_',' '))}</td><td>${safe(f.metadata?.services?.join(', ')||'See evidence')}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No facilities were extracted from the available evidence.</td></tr>'; map(geography); sourcesView(sources); analyses(report,project); dossier(report,project); }
  function map(geography) { const mapElement=get('map'), detail=get('facility-detail'); const target=geography?.target; const facilities=[...(geography?.facilities_inside_radius||[]),...(geography?.facilities_outside_radius||[])]; get('map-title').textContent=target?.location?`Facility map · ${target.location}`:'Facility map'; if(!geography){mapElement.innerHTML='<p class="empty">Geographic analysis is unavailable for this project.</p>';detail.textContent='No geographic analysis was returned by the backend.';return;} if(!facilities.length){mapElement.innerHTML='<p class="empty">No facility coordinates are available from the collected evidence.</p>';detail.textContent='Coordinates were unavailable; no locations were invented.';return;} const lats=facilities.map(f=>f.latitude),lons=facilities.map(f=>f.longitude),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons); mapElement.innerHTML=facilities.map((f,index)=>`<button class="map-point" type="button" aria-label="View ${safe(f.name)}" data-index="${index}" data-name="${safe(f.name)}" style="left:${((f.longitude-minLon)/(maxLon-minLon||1))*76+12}%;top:${88-((f.latitude-minLat)/(maxLat-minLat||1))*76}%"></button>`).join(''); detail.textContent='Select a facility marker to view its evidence-bound details.'; mapElement.querySelectorAll('.map-point').forEach(marker=>marker.addEventListener('click',()=>{const f=facilities[Number(marker.dataset.index)],source=f.source_evidence; detail.classList.remove('empty');detail.innerHTML=`<strong>${safe(f.name)}</strong><dl><dt>Address</dt><dd>${safe(f.address||[f.city,f.state].filter(Boolean).join(', ')||'Not documented')}</dd><dt>Services</dt><dd>${safe((f.services||[]).join(', ')||'Not documented')}</dd><dt>Distance</dt><dd>${f.distance_km==null?'Unavailable':`${safe(f.distance_km)} km`}</dd><dt>Source</dt><dd>${source?`<a href="${safe(source.source_url)}" target="_blank" rel="noopener">${safe(source.source_title)}</a>`:'Evidence source unavailable'}</dd></dl>`;})); }
  function analyses(report,project) { const gaps=report?.service_gaps||[],conflicts=report?.conflicts||[],assessments=project.intermediate_results?.service_gap_assessments||[]; get('service-list').innerHTML=assessments.length?assessments.map(a=>`<div class="item"><strong>${safe(a.service)}</strong><p>${safe(a.summary||a.status)}</p></div>`).join(''):'<div class="empty">No service-level availability assessment was returned.</div>'; get('gap-list').innerHTML=gaps.length?gaps.map(g=>`<div class="item gap"><strong>${safe(g.service_category||g.service)}</strong><p>${safe(g.description||'Potential service gap recorded with limitations.')}</p></div>`).join(''):'<div class="empty">No potential service gaps were recorded.</div>'; get('conflict-list').innerHTML=conflicts.length?conflicts.map(c=>`<div class="item conflict"><strong>${safe(c.topic)}</strong><p>${safe(c.description)}</p></div>`).join(''):'<div class="empty">No evidence conflicts were detected in this run.</div>'; const missing=project.missing_information||[]; get('missing-info').classList.toggle('hidden',!missing.length); get('missing-info').innerHTML=`<strong>Limitations and missing information</strong><ul>${missing.map(item=>`<li>${safe(item)}</li>`).join('')}</ul>`; }
  function sourcesView(sources) { get('source-list').innerHTML=sources.length?sources.map(source=>`<article class="source"><a href="${safe(source.url)}" target="_blank" rel="noopener">${safe(source.title)}</a><p>${safe(source.publisher||source.source_type||'Source')} · ${safe(source.url)}</p></article>`).join(''):'<div class="empty">No sources were returned for this research run.</div>'; }
  function dossier(report,project) { const container=get('report-content');container.classList.remove('empty');container.innerHTML=report?`<h3>${safe(report.title)}</h3><p>${safe(report.executive_summary)}</p><p class="helper">${safe(report.methodology_note||'All findings should be reviewed with cited evidence and limitations.')}</p>`:`<h3>Research completed with partial results</h3><p>${safe((project.missing_information||[]).join(' ')||'No final report was returned by the backend.')}</p>`; }
  async function start(event) { event.preventDefault(); const button=document.querySelector('.primary-button'),query=get('research-question').value.trim(),region=get('research-region').value.trim();button.disabled=true;get('form-message').textContent='Running the research pipeline…';try{const project=await api('/api/research',{method:'POST',body:JSON.stringify({query,region:region||null})});const report=project.report_id?await api(`/api/reports/${encodeURIComponent(project.report_id)}`):null;let geography=null;try{geography=await api(`/api/research/${encodeURIComponent(project.research_id)}/geographic-analysis`);}catch(error){project.missing_information=[...(project.missing_information||[]),`Geographic analysis unavailable: ${error.message}`];}display(project,report,geography);get('form-message').textContent=project.status==='completed'?'Research completed.':'Research returned partial results.';}catch(error){get('form-message').textContent=error.message;get('research-alert').textContent=`API error: ${error.message}`;get('research-alert').classList.remove('hidden');get('progress-section').classList.remove('hidden');}finally{button.disabled=false;} }
  function demo(){const project={query:'Demo mode — illustrative frontend layout only',status:'completed',progress:{current_stage:'COMPLETED',completed_stages:stages},intermediate_results:{source_count:0,facility_count:0,service_gap_assessment_count:0},missing_information:['Demo mode uses no locations or evidence. Connect the API for research results.']};const report={title:'Demo research dossier',executive_summary:'Illustrative layout only; this is not a research finding.',facilities:[],sources:[],service_gaps:[],conflicts:[]};display(project,report,null);get('demo-toggle').textContent='Demo mode active — no data';}
  get('research-form').addEventListener('submit',start);get('demo-toggle').addEventListener('click',demo);get('print-report').addEventListener('click',()=>window.print());health();
})();
